### ISSUE TITLE
Add support for coveralls

### ISSUE THREAD

**Issue by fadeenk** [fadeenk/PiTrol#1]
Before I can add support for coveralls we need to do the following
- [x] Decide which version of node we are supporting (Pure Node 6)
- [x] Decide if we are supporting es6 and/or es7 syntax (None)
- [x] Decide on testing framework (mocha/chai?) (Jest)

Based on that I can set up everything and add coveralls

**Comment by AlKass** [comment]
Please create a poll in our Facebook group and have the majority of the developers decide

**Comment by Ahmed-90** [comment]
- Current node LTS would be good and future proof.
- ES6 node LTS supported features only. (to avoid building systems like babel etc.. )
- Jest by Facebook is getting lots of credit maybe give it a try?

**Comment by AlKass** [comment]
@Ahmed-90

**Comment by fadeenk** [comment]
@AlKass someone with access to repo's settings need to add coveralls integration for this repo otherwise it will not work

**Comment by fadeenk** [comment]
closed by #9
