### ISSUE TITLE
[bug] api server port

### ISSUE THREAD

**Issue by AlhasanIQ** [fadeenk/PiTrol#14]
the api server is on a different port but the ajax is trying to get it from the same port

**Comment by fadeenk** [comment]
I dont think there is a bug. The server serves the build folder so you need to first build the frontend `npm run build` then start the server `npm run start:server` or `node server`

**Comment by AlKass** [comment]
The UI is not a standalone service. It is build with 'npm run build' and rendered via an express GET request. The port conflict you say is not a conflict per se. The 3000 port is usef if the react service is run as a standalone service, i.e. If you're modifying the UI with hot-reload enabled.

**Comment by AlhasanIQ** [comment]
yea , i was talking about the live server not the built code

with the live server they will have different ports

we could save the configuration in a .env file and load it to regulate this for faster development ( no `npm run build` each time i want to test)

**Comment by fadeenk** [comment]
@AlhasanIQ I created a PR for you. I might have misunderstood what you meant at first. I think this is what you wanted to be able to develop and have the frontend connected to the backend. Feel free to correct me if I am wrong
