### ISSUE TITLE
Should we turn the project into a lightweight OS?

### ISSUE THREAD

**Issue by AlKass** [fadeenk/PiTrol#32]
Check [this link](https://github.com/nodeos/nodeos) out

**Comment by AlhasanIQ** [comment]
nah

**Comment by fadeenk** [comment]
Also you would lose access to so much functionality that the user might be relying on, people might be using Thier pi as an all in one personal server.

Ex. My pi is my web dev server, it has PHP MySQL nginx and bunch of other little things. If we do our own is then we won't be able to support any of those tools

**Comment by AlKass** [comment]
@fadeenk  made a good point. Sure, let's stick to what we're doing then
